import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :i_see_sea, ISeeSeaWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Grafana setup
config :i_see_sea, ISeeSeaWeb.PromEx,
  manual_metrics_start_delay: :no_delay,
  drop_metrics_groups: [],
  grafana: [
    host: System.get_env("GRAFANA_HOST"),
    auth_token: System.get_env("GRAFANA_TOKEN"),
    upload_dashboards_on_start: true,
    folder_name: "My App Dashboards",
    annotate_app_lifecycle: true
  ]

config :phoenix, :logger, false

config :i_see_sea,
  backend_url: "iliad.vtmis.bg",
  frontend_url: "iliad.vtmis.bg",
  allowed_origins: [
    "iliad.vtmis.bg"
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
